#@data/values-schema
---

#@schema/desc "Configuration for the namespaces the platform will provision and manage."
namespaces:
  #@schema/desc "Details about the namespace to configure."
  - name: ""

#@schema/desc "The `ServiceAccount` to be configured with credentials and roles in each workspace."
service_account: default

#@schema/desc "Settings for the OCI registry that the workspace will use."
oci_registry:
  #@schema/desc "Configuration for the Secret holding the credentials to access the OCI registry."
  secret:
    #@schema/desc "The name of the Secret holding the credentials to access the OCI registry."
    #@schema/validation min_len=1
    name: ""
    #@schema/desc "The namespace of the Secret holding the credentials to access the OCI registry."
    #@schema/validation min_len=1
    namespace: ""

#@schema/desc "Settings for Cosign, used for signing and verifying OCI artifacts."
cosign:
  #@schema/desc "Configuration for the Secret holding the Cosign key pair."
  secret:
    #@schema/desc "The name of the Secret holding the Cosign key pair."
    name: ""
    #@schema/desc "The namespace of the Secret holding the Cosign key pair."
    namespace: ""

#@schema/desc "Configuration to access the Git repositories used in the GitOps workflows."
git:
  #@schema/desc "The Git server hosting the Git repositories used in the GitOps workflows."
  server: https://github.com
  #@schema/desc "Configuration for Git credentials."
  credentials:
    #@schema/desc "The username to access the Git repositories."
    username: ""
    #@schema/desc "The password to access the Git repositories."
    password: ""
  #@schema/desc "Configuration for the Secret holding the Git credentials."
  secret:
    #@schema/desc "The name of the Secret holding the Git credentials."
    #@schema/validation when=lambda _, ctx: ctx.root["git"]["credentials"]["username"] != "" and ctx.root["git"]["credentials"]["password"] != ""
    name: supply-chain-git-credentials
