apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: workspace-provisioner.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: workspace-provisioner.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/workspace-provisioner/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: workspace-provisioner.packages.kadras.io
spec:
  categories:
  - environment provisioning
  displayName: workspace-provisioner
  longDescription: Provisions and configures workspaces for the platform users, such as application developers. A workspace can be a namespace or a virtual cluster.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Provisions and configures workspaces for the platform users.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/workspace-provisioner
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: workspace-provisioner
spec:
  packageRef:
    refName: workspace-provisioner.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
